---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: "3"

env:
  PATH:
    sh: 'echo "$PATH:$(go env GOPATH)/bin"'

vars:
  PROJECT_DIR: "{{.ROOT_DIR}}"
  SOURCE_DIR: "{{.PROJECT_DIR}}/src"
  BUILD_DIR: "{{.PROJECT_DIR}}/bin"

tasks:
  default:
    cmd: task --list
    silent: true
  test:
    desc: Run tests
    cmds:
      - printenv | grep PATH

includes:
  build: .taskfiles/build/Taskfile.yaml
  install: .taskfiles/install/Taskfile.yaml
  lint: .taskfiles/lint/Taskfile.yaml
  run: .taskfiles/run/Taskfile.yaml
  docker: .taskfiles/docker/Taskfile.yaml
