---
version: "3"

tasks:
  build:
    desc: Build docker image
    cmds:
      - docker build -t rest-go:latest .

  run:
    desc: Run docker container
    cmds:
      - docker run -p 8080:8080 rest-go:latest
